name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get all commits to have the right date of last edit for articles

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true

      - run: go version

      - run: apt-get update -y && apt-get upgrade -y

      - run: git log -1 --pretty=format:%cI web/articles/a_unique_opportunity_for_technological_freedom.md

      - name: Run release script
        run: ./.github/scripts/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          tag: ${{ github.ref_name }}
        shell: bash